version: "3.9"

services:

    laravel.test:
        image: kanonhian/bagisto-shop:latest
        container_name: bahisto-app
        restart: unless-stopped
        working_dir: /var/www/html
        ports:
            - "${APP_PORT:-8000}:8000"
            - "${VITE_PORT:-5173}:5173"
        volumes:
            - ./:/var/www/html
        env_file:
            - .env.develop
        depends_on:
            - mariadb
            - redis
            - minio
            - mailpit
        networks:
            - bagisto

    mariadb:
        image: mariadb:11.3
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
            MYSQL_DATABASE: ${DB_DATABASE:-bagisto_shop}
            MYSQL_USER: ${DB_USERNAME:-bagisto}
            MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
        volumes:
            - mariadb-data:/var/lib/mysql
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - bagisto

    redis:
        image: redis:7-alpine
        command: [ "redis-server", "--save", "", "--appendonly", "yes" ]
        restart: unless-stopped
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - redis-data:/data
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - bagisto

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
        ports:
            - '9200:9200'
            - '9300:9300'
        environment:
            - xpack.security.enabled=false
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        volumes:
            - 'data-elasticsearch:/var/lib/elasticsearch/data'
        networks:
            - bagisto
    kibana:
        image: docker.elastic.co/kibana/kibana:7.17.0
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
        networks:
            - bagisto
        depends_on:
            - elasticsearch

    minio:
        image: minio/minio:latest
        command: server /data --console-address ":9001"
        restart: unless-stopped
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
        ports:
            - "${MINIO_PORT:-9000}:9000"
            - "${MINIO_CONSOLE_PORT:-9001}:9001"
        volumes:
            - minio-data:/data
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
            interval: 30s
            timeout: 20s
            retries: 5
        networks:
            - bagisto

    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - bagisto

networks:
    bagisto:
        driver: bridge
        ipam:
            config:
                - subnet: 172.30.10.0/24   # pick a range not used anywhere else

volumes:
    mariadb-data:
    redis-data:
    minio-data:
    data-elasticsearch:
