name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Inject secret environment variables
        run: |
          {
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}";
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}";
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}";
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}";
          #  echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}";
          #  echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}";
          } >> .env 

      - name: Generate key
        run:  php artisan key:generate

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: kanonhian/bagisto-shop:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
